spring:
  application.name: integrations.imc
  config.name: application

  main:
    web-environment: true
    show-banner: true
    log-startup-info: true

security:
    basic.enabled: true
    
management:
    contextPath: /mgmt

server:
  port: 9085

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE